[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cane"
version = "0.1.1"
description = "Contrail Avoidance Non-CO2 Evaluation"
authors = [
    { name = "Jakob Smretschnig", email = "j.smretschnig@tudelft.nl" }
]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "airportsdata>=20240316.1",
    "geopy>=2.4.1",
    "matplotlib>=3.10.8",
    "notebook>=7.5.5",
    "pip>=26.0.1",
    "pycontrails[complete]>=0.54.11",
    "seaborn>=0.13.2"
]

[tool.setuptools.packages.find]
where = ["src"]
